#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V  

bspc config border_width         3
bspc config window_gap           0
bspc config top_padding		 0

bspc config normal_border_color "#44475a"
bspc config active_border_color "#5e81ac"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
picom &
feh --bg-fill --randomize ~/Pictures/wallpapers/*
$HOME/.config/polybar/launch.sh
setxkbmap -layout es
wmname LG3D
