#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap           12
bspc config top_padding		 0

bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a android-studio desktop='^2' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
picom &
feh --bg-fill --randomize ~/Pictures/wallpapers/*
$HOME/.config/polybar/launch.sh
setxkbmap -layout es
wmname LG3D
flameshot
